### ISSUE TITLE
（３－１）Primary / Secondary / Tertiaryカラーの設定

### ISSUE THREAD

**Issue by yoko-at-home** [mo-ri-regen/qin-todo-frontend#13]
**### ゴール**

- tailwind.config.jsにThemeにカラーを設定する。

参考
Primary:  #F43F5E
Secondary: #FB923C
Tertiary: #FBBF24

**Comment by takasaki376** [comment]
後でよいと思います。まずは、簡易的にTODOを登録できる状態を直近のゴールとしましょう。

**Comment by takasaki376** [comment]
対応概要３－１の中にもダークモード対応を追加しました。
